pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/krpalgithub/simple-java-maven-app.git "
            }
        }
        stage("Build"){
            steps {
                directory("simple-java-maven-app") {
                        sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps {
                directory("simple-java-maven-app") {
                        sh "mvn test"
                }
            }
        }
    }


}
